Update UG from Draft UG
AY2324S1-CS2103T-W09-2/tp pull request #16
Opened 2023-10-01 08:59 UTC by dloh2236

Add UG for Contacts Management, test MarkBind formatting

2023-10-02 04:48 UTC, flexibo requested changes

2023-10-02 04:48 UTC, flexibo commented on docs/UserGuide.md
> +|  `PHONE_NUMBER`   | Numeric values<br>(optional "+" prefix)                                                                        | #g#81234567##<br>#g#+6581234567##<br>#r#A0u38niufd##<br>#r#(phon
Maybe can make use of this instead

```diff
+ Annie Dunkins
+ 'Chewbaca' The 1st
+ 81234567
- A0u38niufd (phone number cannot contain alphabets)
```

2023-10-02 04:48 UTC, flexibo commented on docs/UserGuide.md
> +</box>
> [!NOTE]
> * [a/ADDRESS]` should preferably be the company’s address
> * Note that each contact can have:
>     * At most one `[a/ADDRESS]`
>     * At most one `[c/COMPANY]` 
>     * At most one `[t/TELEGRAM_NAME]`

2023-10-02 04:48 UTC, flexibo commented on docs/UserGuide.md
> +</box>
> [!NOTE]
> * Using partial keywords will be matched. e.g. 'ha' will match 'hans'
> * The search is case-insensitive. e.g `hAnS` will match `Hans`
> * The order of the keywords does not matter. e.g. `Hans Bo` will match `Bo Hans`
> * Only the name is searched.
> * Persons matching at least one keyword will be returned (i.e. `OR` search).
>     * e.g. `Hans Bo` will return `Hans Gruber`, `Bo Yang`

2023-10-04 01:47 UTC, merged

2023-10-04 01:47 UTC, nicholascher commented
LGTM.